已连接到 Python 3.11.8

In [1]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.8176, 0.5313, 0.4715],
        [0.4796, 0.7230, 0.9092],
        [0.1951, 0.0724, 0.5360],
        [0.6708, 0.4912, 0.8863],
        [0.3646, 0.3083, 0.6372]])


In [2]:
torch.cuda.is_available()

True

In [7]:
from torchvision import models
dir(models)

['AlexNet',
 'AlexNet_Weights',
 'ConvNeXt',
 'ConvNeXt_Base_Weights',
 'ConvNeXt_Large_Weights',
 'ConvNeXt_Small_Weights',
 'ConvNeXt_Tiny_Weights',
 'DenseNet',
 'DenseNet121_Weights',
 'DenseNet161_Weights',
 'DenseNet169_Weights',
 'DenseNet201_Weights',
 'EfficientNet',
 'EfficientNet_B0_Weights',
 'EfficientNet_B1_Weights',
 'EfficientNet_B2_Weights',
 'EfficientNet_B3_Weights',
 'EfficientNet_B4_Weights',
 'EfficientNet_B5_Weights',
 'EfficientNet_B6_Weights',
 'EfficientNet_B7_Weights',
 'EfficientNet_V2_L_Weights',
 'EfficientNet_V2_M_Weights',
 'EfficientNet_V2_S_Weights',
 'GoogLeNet',
 'GoogLeNetOutputs',
 'GoogLeNet_Weights',
 'Inception3',
 'InceptionOutputs',
 'Inception_V3_Weights',
 'MNASNet',
 'MNASNet0_5_Weights',
 'MNASNet0_75_Weights',
 'MNASNet1_0_Weights',
 'MNASNet1_3_Weights',
 'MaxVit',
 'MaxVit_T_Weights',
 'MobileNetV2',
 'MobileNetV3',
 'MobileNet_V2_Weights',
 'MobileNet_V3_Large_Weights',
 'MobileNet_V3_Small_Weights',
 'RegNet',
 'RegNet_X_16GF_Weights'

In [8]:
# 使用ResNet 图像分类模型
resnet = models.resnet101(pretrained = True)

c:\Python311\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Python311\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet101_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet101_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [16]:
# 图片识别归类，下面例子读取一张图片利用ResNet模型识别图片属于什么类目
from torchvision import transforms
from torchvision import models
from PIL import Image
import torch

# 组合图像转换操作
# 定义转换属性，调整大小，中心裁剪，对图片进行标准化等
preprocess = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(
    mean=[0.485, 0.456, 0.406],
    std=[0.229, 0.224, 0.225])
])

resnet = models.resnet101(pretrained = True)

# 打开图片
img = Image.open('./data/dog.jpeg')

# 转换图片
img_t = preprocess(img)

# 调整张量的维度和形状，在第0维插入新的维度
batch_t = torch.unsqueeze(img_t,0)
# 把图像放入模型中，设置处理模式eval模式（评估模式，还有训练模式）
resnet.eval()
# 输出
out = resnet(batch_t)
# 加载类别信息
with open('./data/imagenet_classes.txt') as f:
    labels = [line.strip() for line in f.readlines()]
# 在张量中找到指定维度的最大值以及它们的位置
_,index = torch.max(out,1)
# 输出类别和对应的置信度
percentage = torch.nn.functional.softmax(out,dim=1)[0]*100
labels[index[0]],percentage[index[0]].item()

# 将置信度按照从大到小进行排序，取前五个
_,indices = torch.sort(out,descending=True)
[(labels[idx],percentage[idx].item()) for idx in indices[0][:5]] 


c:\Python311\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Python311\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet101_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet101_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


[('golden retriever', 96.18659973144531),
 ('Labrador retriever', 2.625396728515625),
 ('redbone', 0.6544859409332275),
 ('cocker spaniel, English cocker spaniel, cocker', 0.1351047158241272),
 ('tennis ball', 0.07312993705272675)]

In [26]:
# 张量
import torch

# 构建一个全是1的张量数组
double_points = torch.ones(10,2,dtype=torch.double)
# 根据二维数组构建tensor张量对象
short_point = torch.tensor([[1,2],[3,4]],dtype=torch.short)
double_points,short_point,short_point.dtype

# 强制转换
short_to_double = short_point.to(torch.double)
print(short_point,short_to_double)

# 将张量存储倒GPU
points_gpu = torch.tensor([[1,2,3],[4,5,6],[7,8,9]],device='cuda')
print(points_gpu)
points_gpu0 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]],device='cuda:0')
print(points_gpu0)

# 将数据回传到cpu
points_cpu = points_gpu.to(device='cpu')
print(points_cpu)




tensor([[1, 2],
        [3, 4]], dtype=torch.int16) tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], device='cuda:0')
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], device='cuda:0')
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
